/**:
  kt_server_client_node:
    ros__parameters:
      robot_serial: "RSN800-0000"
      client_id: "snsolutions"
      client_secret: "QgvVztMwFggaC3Ds1nDCgIXec9P5Ca84"
      report_hz: 1.0
      verbose: true


      fb_min_lat: 36.114035673055845 # first gnss wp
      fb_min_lon: 128.41830360303496 # first gnss wp
      fb_max_lat: 36.1140370525463946 # last gnss wp
      fb_max_lon: 128.41826355116552 # last gnss wp
